config/routes.rb
CodefellowsTest::Application.routes.draw do
  resources :user_question_sets

  resources :user_enrollments

  resources :questions do
    resources :answers
  end

  resources :offerings

  devise_for :users
  get '/user_enrollments' => 'user_enrollments#delete_user', as: 'delete_user'

  devise_scope :users do
    delete '/users/sign_out' => 'devise/sessions#destroy'
  end

   root 'offerings#index'

end

app/models/offering.rb
class Offering < ActiveRecord::Base
	belongs_to :user_enrollment

end

app/controllers/offerings_controller.rb
class OfferingsController < ApplicationController
  before_action :set_offering, only: [:show, :edit, :update, :destroy]

  # GET /offerings
  # GET /offerings.json
  def index
    @offerings = Offering.all
  end

  # GET /offerings/1
  # GET /offerings/1.json
  def show

  end

  # GET /offerings/new
  def new
    @offering = Offering.new
  end

  # GET /offerings/1/edit
  def edit
  end

  # POST /offerings
  # POST /offerings.json
  def create
    @offering = Offering.new(offering_params)

    respond_to do |format|
      if @offering.save
        format.html { redirect_to @offering, notice: 'Offering was successfully created.' }
        format.json { render action: 'show', status: :created, location: @offering }
      else
        format.html { render action: 'new' }
        format.json { render json: @offering.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offerings/1
  # PATCH/PUT /offerings/1.json
  def update
    respond_to do |format|
      if @offering.update(offering_params)
        format.html { redirect_to @offering, notice: 'Offering was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @offering.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offerings/1
  # DELETE /offerings/1.json
  def destroy
    @offering.destroy
    respond_to do |format|
      format.html { redirect_to offerings_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_offering
      @offering = Offering.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def offering_params
      params.require(:offering).permit(:name, :offering_type_id, :city_id, :description, :location_id,
                                       :starts_at, :ends_at, :max_enrollment, :created_at, :updated_at,
                                       :deadline_at, :tuition_cost, :deposit_cost, :code, :user_enrollment_id,
                                       :language_type)
    end
end

app/helpers/offerings_helper.rb
module OfferingsHelper
end

app/views/offerings/_form.html.erb
<%= form_for(@offering) do |f| %>
  <% if @offering.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@offering.errors.count, "error") %> prohibited this offering from being saved:</h2>

      <ul>
      <% @offering.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :offering_type_id %><br>
    <%= f.number_field :offering_type_id %>
  </div>
  <div class="field">
    <%= f.label :city_id %><br>
    <%= f.text_field :city_id %>
  </div>
  <div class="field">
    <%= f.label :location_id %><br>
    <%= f.text_field :location_id %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div  class="field">
    <%= f.label :starts_at %><br>
    <%= f.date_field :starts_at %>
  </div>
  <div  class="field">
    <%= f.label :ends_at %><br>
    <%= f.date_field :ends_at %>
  </div>
  <div  class="field">
    <%= f.label :created_at %><br>
    <%= f.date_field :created_at %>
  </div>
  <div class="field">
    <%= f.label :max_enrollment %><br>
    <%= f.number_field :max_enrollment %>
  </div>
  <div  class="field">
    <%= f.label :deadline_at %><br>
    <%= f.date_field :deadline_at %>
  </div>
  <div class="field">
    <%= f.label :tuition_cost %><br>
    <%= f.text_field :tuition_cost %>
  </div>
  <div class="field">
    <%= f.label :deposit_cost %><br>
    <%= f.text_field :deposit_cost %>
  </div>
  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :user_enrollment_id %><br>
    <%= f.number_field :user_enrollment_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/offerings/edit.html.erb
<h1>Editing offering</h1>

<%= render 'form' %>

<%= link_to 'Show', @offering %> |
<%= link_to 'Back', offerings_path %>

app/views/offerings/index.html.erb
<h1>Listing offerings</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Start Date</th>
      <th>End Date</th>
      <th>Offering Type</th>
      <th>City</th>
      <th>Location</th>
      <th>Description</th>
      <th>Max Enrollment</th>
      <th>Created At</th>
      <th>Updated At</th>
      <th>Deadline At</th>
      <th>Tuition Cost</th>
      <th>Deposit Cost</th>
      <th>Code</th>
      <th>User Enrollment ID</th>
      <th>Language Type</th>
    </tr>
  </thead>

  <tbody>
    <% @offerings.each do |offering| %>
      <tr>
        <td><%= offering.name %></td>
        <td><%= offering.starts_at %></td>
        <td><%= offering.ends_at %></td>
        <td><%= offering.offering_type_id %></td>
        <td><%= offering.city_id %></td>
        <td><%= offering.location_id %></td>
        <td><%= offering.description %></td>
        <td><%= offering.max_enrollment %></td>
        <td><%= offering.created_at %></td>
        <td><%= offering.updated_at %></td>
        <td><%= offering.deadline_at %></td>
        <td><%= offering.tuition_cost %></td>
        <td><%= offering.deposit_cost %></td>
        <td><%= offering.code %></td>
        <td><%= offering.user_enrollment_id %></td>
        <td><%= offering.language_type %></td>
        <td><%= link_to 'Show', offering %></td>
        <td><%= link_to 'Edit', edit_offering_path(offering) %></td>
        <td><%= link_to 'Destroy', offering, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Offering', new_offering_path %>


<% if current_user %>
  <% if current_user.user_enrollment%>
    <%= link_to "View application",user_enrollment_path(current_user.user_enrollment)%>
  <%else %>
    <%= link_to "Apply now",new_user_enrollment_path%>
  <% end %>
<% end %>

app/views/offerings/new.html.erb
<h1>New offering</h1>

<%= render 'form' %>

<%= link_to 'Back', offerings_path %>

app/views/offerings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @offering.name %>
</p>

<p>
  <strong>Offering Type:</strong>
  <%= @offering.offering_type_id %>
</p>

<p>
  <strong>City:</strong>
  <%= @offering.city_id %>
</p>

<p>
  <strong>Location:</strong>
  <%= @offering.location_id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @offering.description %>
</p>

<p>
  <strong>Start Date:</strong>
  <%= @offering.starts_at %>
</p>


<p>
  <strong>End Date:</strong>
  <%= @offering.ends_at %>
</p>

<p>
  <strong>Max Enrollment:</strong>
  <%= @offering.max_enrollment %>
</p>


<!-- #.strftime("%b %e, %Y %l:%m%p") this is how you display time differently look at http://apidock.com/ruby/DateTime/strftime-->

<p>
  <strong>Created:</strong>
  <%= @offering.created_at %>
</p>

<p>
  <strong>Updated:</strong>
  <%= @offering.updated_at %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @offering.deadline_at %>
</p>

<p>
  <strong>Tuition Cost:</strong>
  <%= @offering.tuition_cost %>
</p>

<p>
  <strong>Deposit Cost:</strong>
  <%= @offering.deposit_cost %>
</p>

<p>
  <strong>Code:</strong>
  <%= @offering.code %>
</p>

<p>
  <strong>User Enrollment:</strong>
  <%= @offering.user_enrollment_id %>
</p>

<p>
  <strong>Language Type:</strong>
  <%= @offering.language_type %>
</p>

<%= link_to 'Edit', edit_offering_path(@offering) %> |
<%= link_to 'Back', offerings_path %>